### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lz00qs**

### CODE REVIEW

**Comment by lz00qs** [comment]
merge dev

**Comment by 7Ji** [comment]
Knowing this is a incorrectly opened PR, I still have some points here:
  - The `native_build` method is unmaintained after I switched the repo to `cross_nobuild` as I started to host [my own package repo](https://github.com/7Ji/archrepo). It had some un-fixed overlooked issues, notably about package rebuilding. It should work as how it worked before the switch, but I won't fix it if it breaks in the future.
  - If you're creating your own distro-packing repo, I don't recommend to base that repo on any of my repo, rather you should create a new one instead of forking from my repo, as you shouldn't need device-specific codes here, all they do is messing up your project structure and history. E.g. [orangepi5-archlinuxarm](https://github.com/7Ji/orangepi5-archlinuxarm) lies in its own repo
  - If your kernel package is stable and you decide to push that to AUR, you can open a PR on my [archrepo](https://github.com/7Ji/archrepo) to add it to the aarch64 build list.

**Comment by lz00qs** [comment]
> Knowing this is a incorrectly opened PR, I still have some points here:
> 
> * The `native_build` method is unmaintained after I switched the repo to `cross_nobuild` as I started to host [my own package repo](https://github.com/7Ji/archrepo). It had some un-fixed overlooked issues, notably about package rebuilding. It should work as how it worked before the switch, but I won't fix it if it breaks in the future.
> * If you're creating your own distro-packing repo, I don't recommend to base that repo on any of my repo, rather you should create a new one instead of forking from my repo, as you shouldn't need device-specific codes here, all they do is messing up your project structure and history. E.g. [orangepi5-archlinuxarm](https://github.com/7Ji/orangepi5-archlinuxarm) lies in its own repo
> * If your kernel package is stable and you decide to push that to AUR, you can open a PR on my [archrepo](https://github.com/7Ji/archrepo) to add it to the aarch64 build list.
First of all, sorry for my reckless merge request. Thank you very much for the reminder, my current development goal is to adapt Archlinux to the orangepi zero3 I have, I'll take your suggestion into consideration when I've got the bootloader related packages and kernels available!

First of all, sorry for my reckless merge request. Thank you very much for the reminder, my current development goal is to adapt Archlinux to the orangepi zero3 I have, I'll take your suggestion into consideration when I've got the bootloader related packages and kernels available!

**Comment by 7Ji** [comment]
Hello, I have recently changed a few things in both this and orangepi5 project, and I think downstream should be notified of them. But since you're the only active downstream I'll just write here.

1. The old native_build.sh was killed for good and completely dropped.
2. Both of the projects now use user namespaces to build images without any root permission. You might want to check https://github.com/7Ji/orangepi5-archlinuxarm/blob/master/cross_nobuild.sh , where most of the development happens.
3. My repo is now open to package submits https://github.com/7Ji/archrepo#contribution
4. Due to recent purging of ARM-only packages from AUR, I've migrated all my PKGBUILDs to https://github.com/7Ji-PKGBUILDs , you might want to change your PKGBUILDs' upstream.
5. I've migrated to a new -git kernel package for the OPi5 project, as OPi's revisoning doesn't make sense any more: https://github.com/7Ji-PKGBUILDs/.report/issues/5

**Pull request closed without merging**
