### PR TITLE
Update release.yml

### PR DESCRIPTION
**Pull request by sajjadsabzkar**
update release.yaml to direct each night's release to the release section in repo

### CODE REVIEW

**Comment by 7Ji** [comment]
Do we even need old images for a rollong release distro? I made it only one release on purpose to save GH's release.

**Comment by sajjadsabzkar** [comment]
The last image uploaded in the GitHub release is from a long time ago and it is not possible to find the latest changes in that image. It may be useful for testing and updating new items

**Comment by 7Ji** [comment]
No, the image is always built nightly. The only thing old is the tag, which is only tagged once.

**Comment by 7Ji** [comment]
I don't like when GH actions push changes to a git repo. That's why I don't let actions create tags. I only create tag once, and every new build artifact, although built against the latest commit, is always pushed to the same tag. The release time is the time of the tag, which I don't find useful retagging again and again.

**Comment by sajjadsabzkar** [comment]
But how can you be sure that the latest changes in your repository are compatible with the previous changes? For example, in [openvfd issues](https://github.com/7Ji/amlogic-s9xxx-archlinuxarm/issues/21) openvfd is disabled and it is not clear which part of the code causes the problem? Don't you think it makes debugging easier? Although, every now and then you have to clear the nightly rails.

**Comment by sajjadsabzkar** [comment]
> No, the image is always built nightly. The only thing old is the tag, which is only tagged once.

But your last GH release before 2024 was built at night.

**Comment by 7Ji** [comment]
> But how can you be sure that the latest changes in your repository are compatible with the previous changes?

I can't. Because I don't want to freeze things up: if things are broken, fix them up, instead of freezing the stuffs and pretending there's no issue.

> Don't you think it makes debugging easier
> But your last GH release before 2024 was built at night.

That's not how my actions work. The release is created and never deleted. Every day a workflow is triggered to rebuild the image from latest commit, and the release artifacts are replaced by new files. 

Tracking things by date does not improve debugging much, because commit is still not tracked. And tracking commit alongside date also does not do much: a commit + a date would not result in a reproducible image in any way, the product would always be affected by the mirror state and the state of my arch repo.

A side note: please learn about the relationship between a git tree, a git commit (referencing a git tree), a git tag (referencing a git commit) and a github release (loosely referencing a git tag, but can contain any thing user uploads)

**Pull request closed without merging**
